### ISSUE TITLE
不会Java但一定要学习的阿里中间件

### ISSUE THREAD

**Issue by itherunder** [itherunder/blog#30]
### 搭集群
1. 下载[RocketMQ 4.9.0](http://rocketmq.apache.org/)，`bin`和`source`都下下来
2. 先单机跑一下：a) `name server`，类似于注册中心，`rocketmq-all-4.9.0-bin-release/bin/mqnamesrv -n localhost:9876`；b) `broker`，用来中间处理消息的，`rocketmq-all-4.9.0-bin-release/bin/mqbroker -c path/to/conf`，有个`conf`文件用来设置主从、`brokerName`，`brokerClusterName`之类的，重要的是要设置`namesrvAddr=127.0.0.1:9876`和自己的`listenPort`(默认10911)
![image](https://user-images.githubusercontent.com/61953384/123401532-7c011f80-d5d9-11eb-8fbc-ce5573a9ec10.png)
```conf
brokerClusterName=DefaultCluster
brokerName=broker0
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

# dleger
enableDLegerCommitLog=true
dLegerGroup=broker0
dLegerPeers=n0-broker0n0:40911;n1-broker0n1:40911;n2-broker0n2:40911
dLegerSelfId=n0
sendMessageThreadPoolNums=4

# namesrv的地址和端口，这里设置为虚拟机的IP，以便于让测试机访问
namesrvAddr=127.0.0.1:9876
# 该broker的IP地址，由于测试需要让其他机器访问，因此设置为虚拟机的IP
brokerIP1=127.0.0.1
listenPort=10911
```
3. 下载`docker`，`brew install --cask docker`即可
4. 编写`rocketmq-namesrv.dockerfile`和`rocketmq-broker.dockerfile`，精髓，学习到了很多东西，然后就可以`docker build -f xx.dockerfile -t xx:0.1 .`搞一个新的镜像了，注意最后有一个点
```dockerfile
FROM openjdk:8u292-jdk

LABEL MAINTAINER='nstl.liaozhou'

ADD rocketmq-all-4.9.0-bin-release /app/rocketmq

ENTRYPOINT exec sh /app/rocketmq/bin/mqnamesrv -n 127.0.0.1:9876
RUN echo "Asia/Shanghai" > /etc/timezone

EXPOSE 9876
```

```dockerfile
FROM openjdk:8u292-jdk

LABEL MAINTAINER='nstl.liaozhou'

ADD rocketmq-all-4.9.0-bin-release /app/rocketmq
RUN echo "Asia/Shanghai" > /etc/timezone

ENTRYPOINT exec sh /app/rocketmq/bin/mqbroker -c /app/rocketmq/conf/broker.conf
VOLUME /app/data
```
5. 编写`docker-compose.yml`，也是精髓，学到了很多东西，然后就可以`docker-compose up`直接跑起来`docker`了，三大件`version, services, networks`，`services`里面每一个儿子都是一个`container`，`build`可以直接代替上面的`docker build`并且将这个镜像命名成下一行的`image: rocketmq-namesrv`，酱
```yml
version: '3.5'
services:
    # 一个name server
    namesrv:
        build:
            context: .
            dockerfile: rocketmq-namesrv.dockerfile
        image: rocketmq-namesrv
        container_name: namesrv
        restart: always
        networks:
            rocketmq-dledger:
        ports:
            - 9876:9876
        volumes:
            - ./logs_store/namesrv:/app/data
    
    # 一个rocketmq console
    console:
        image: styletang/rocketmq-console-ng
        container_name: rocketmq-console
        depends_on:
            - namesrv
        environment:
            - JAVA_OPTS=-Dlogging.level.root=info -Drocketmq.namesrv.addr=namesrv:9876
            - Dcom.rocketmq.sendMessageWithVIPChannel=false
        networks:
            rocketmq-dledger:
        ports:
            - 8087:8080

    # broker0
    broker0-n0:
        build:
            context: .
            dockerfile: rocketmq-broker.dockerfile
        image: rocketmq-broker
        container_name: broker0n0
        restart: always
        depends_on:
            - namesrv
        networks:
            rocketmq-dledger:
        volumes: 
            - ./broker-conf/broker0-n0.conf:/app/rocketmq/conf/broker.conf
            - ./logs_store/broker0n0:/app/data
        ports: 
            - 10909:10909
            - 10911:10911
            - 10912:10912
networks:
    rocketmq-dledger:
```
